<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_pemilih</name>
   <tag></tag>
   <elementGuidId>7acdde7a-790d-43d6-8761-eb3605c8cbdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Statusradio']/label[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>81e8b84d-2935-46e7-83f2-96591f376669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Statusradio&quot;)/label[@class=&quot;radio&quot;]/span[1]</value>
      <webElementGuid>baf59656-0ade-49fe-bad8-6c11fc46feed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Statusradio']/label[2]/span</value>
      <webElementGuid>7ad8aa96-6a67-46b5-815e-22edc1bf8900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/label[2]/span</value>
      <webElementGuid>1520c21c-3dd7-4506-b6fa-0143619ebd7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
