<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_laki</name>
   <tag></tag>
   <elementGuidId>435d1809-554a-40ca-a7a6-34ebd616ec66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.radio > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form_inputpemilih']/div/div/div[2]/div[3]/div/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>05a77c38-a94e-4e2f-b544-0003e3b513b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_inputpemilih&quot;)/div[@class=&quot;card-body&quot;]/div[@class=&quot;row col-12&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-group row fv-plugins-icon-container&quot;]/div[@class=&quot;col-8 col-form-label&quot;]/div[@class=&quot;radio-inline&quot;]/label[@class=&quot;radio&quot;]/span[1]</value>
      <webElementGuid>b0bf127f-add6-4a38-af80-d4699e98d1fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_inputpemilih']/div/div/div[2]/div[3]/div/div/label/span</value>
      <webElementGuid>9b365efe-71c1-4bec-a2e0-e4aed7776a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/label/span</value>
      <webElementGuid>e77323d8-b2fa-4b42-a356-44c710d970eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
