<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_perempuan</name>
   <tag></tag>
   <elementGuidId>527715a3-b1c8-42f1-928c-f7c65913af67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form_inputpemilih']/div/div/div[2]/div[3]/div/div/label[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a88eeedd-4e87-49c0-a021-1513c8724265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_inputpemilih&quot;)/div[@class=&quot;card-body&quot;]/div[@class=&quot;row col-12&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-group row fv-plugins-icon-container&quot;]/div[@class=&quot;col-8 col-form-label&quot;]/div[@class=&quot;radio-inline&quot;]/label[@class=&quot;radio&quot;]/span[1]</value>
      <webElementGuid>fe65772f-9b3f-431a-a453-d82405f0d193</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_inputpemilih']/div/div/div[2]/div[3]/div/div/label[2]/span</value>
      <webElementGuid>6767705d-9778-4bea-b205-ca96f28972c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span</value>
      <webElementGuid>7af68009-bf65-4945-a04f-d8002fde63b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
