<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Bengkulu</name>
   <tag></tag>
   <elementGuidId>2a99c7d3-aa81-4737-90fd-a34b0aaddb20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-filter_provinsi_id-result-lntr-7fd2c16526aa7c1ab7a409a99590438c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-filter_provinsi_id-result-lntr-7fd2c16526aa7c1ab7a409a99590438c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0a39c0f5-6472-4af2-b2ba-432277bc5098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>c19685b9-8dc2-42e9-9213-6d1923a8430e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-filter_provinsi_id-result-lntr-7fd2c16526aa7c1ab7a409a99590438c</value>
      <webElementGuid>22a1a021-1c8f-4ec2-8cdf-669b08dd4679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>64ccf837-7397-4d8b-b870-b022594b00db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ce0dd150-fde1-4dc7-9f83-08eae3935c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-filter_provinsi_id-result-lntr-7fd2c16526aa7c1ab7a409a99590438c</value>
      <webElementGuid>b9e23175-b732-4246-b988-536038eac325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bengkulu</value>
      <webElementGuid>839b0e33-c62e-4049-851f-5ae92d60ab0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-filter_provinsi_id-result-lntr-7fd2c16526aa7c1ab7a409a99590438c&quot;)</value>
      <webElementGuid>420e1eaf-09cc-43ae-9e5d-f1600e219f34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-filter_provinsi_id-result-lntr-7fd2c16526aa7c1ab7a409a99590438c']</value>
      <webElementGuid>86755511-5ac9-4bc0-b82e-392208677c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-filter_provinsi_id-results']/li[4]</value>
      <webElementGuid>407ca611-dee6-4dfa-bd89-163ab905ab2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bali'])[4]/following::li[1]</value>
      <webElementGuid>ef564c36-4678-402b-b6e0-7ec92256280f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bali'])[3]/following::li[2]</value>
      <webElementGuid>5f50c81c-6182-4a05-be95-11fb86c26263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jakarta'])[2]/preceding::li[1]</value>
      <webElementGuid>40e35c4e-dccb-4872-a62d-a4983367709f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jawa Barat'])[2]/preceding::li[2]</value>
      <webElementGuid>69d3fda5-2d05-4175-bae2-2e05a68daa70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li[4]</value>
      <webElementGuid>7011dd83-208d-46b6-839d-8c969fc6231d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-filter_provinsi_id-result-lntr-7fd2c16526aa7c1ab7a409a99590438c' and (text() = 'Bengkulu' or . = 'Bengkulu')]</value>
      <webElementGuid>9a4f51c9-3ae1-428e-8842-734eefbbd77c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
