<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Baru</name>
   <tag></tag>
   <elementGuidId>37120435-d25f-47e9-aeb1-31daeb4ec1ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id = 'select2-filter_tps_id-result-uwdw-157a589039f3122afa511f1bc311e499' and (text() = 'Baru' or . = 'Baru')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4d7b5951-3e9b-44ad-97d4-d369c1cd4323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>8dcd62e4-36ea-4994-a8a9-0b05c10c3729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-filter_tps_id-result-uwdw-157a589039f3122afa511f1bc311e499</value>
      <webElementGuid>1d5914cf-8f7e-44c2-8ac7-7642cc7149d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>0e07e033-8681-423f-86f2-5040c2320558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7cf1b5da-5e31-4659-9b2b-627f0685df80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-filter_tps_id-result-uwdw-157a589039f3122afa511f1bc311e499</value>
      <webElementGuid>41ecb79b-8f9d-4750-8e46-a7f0ae5518d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Baru</value>
      <webElementGuid>60fc261d-cca2-4343-bcdd-f9e1dada737c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-filter_tps_id-result-uwdw-157a589039f3122afa511f1bc311e499&quot;)</value>
      <webElementGuid>27286b42-2593-4fbe-adf4-0307ae49ec84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-filter_tps_id-result-uwdw-157a589039f3122afa511f1bc311e499' and (text() = 'Baru' or . = 'Baru')]</value>
      <webElementGuid>e74f6220-85e9-45b2-9906-2e08b9d52be2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
