<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Curup</name>
   <tag></tag>
   <elementGuidId>ea53d4b7-42dc-41e8-91af-a0da4fb4e7ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id = 'select2-filter_kecamatan_id-result-mcaw-fe467539d00d70126ae69a5c62a9ab5e' and (text() = 'Curup' or . = 'Curup')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>06c1d987-a330-485d-8196-6f7f6e84ecce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>d13e1d25-fd73-4b06-a338-3c7d3e0ad0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-filter_kecamatan_id-result-mcaw-fe467539d00d70126ae69a5c62a9ab5e</value>
      <webElementGuid>8b8a80a0-b3ad-4af6-ae7f-bb014041a131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>51934c8c-5449-411a-b9f0-12f0c88e6d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0c573433-e1ab-4829-99b9-c7f1a3f3a2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-filter_kecamatan_id-result-mcaw-fe467539d00d70126ae69a5c62a9ab5e</value>
      <webElementGuid>83185f03-b519-471c-b869-eb5775d32f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Curup</value>
      <webElementGuid>4f210777-4aad-4391-a065-1db2e30a33e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-filter_kecamatan_id-result-mcaw-fe467539d00d70126ae69a5c62a9ab5e&quot;)</value>
      <webElementGuid>47f1c095-4fcc-441f-8d09-6efeefa4d85d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-filter_kecamatan_id-result-mcaw-fe467539d00d70126ae69a5c62a9ab5e' and (text() = 'Curup' or . = 'Curup')]</value>
      <webElementGuid>37ed1928-16f4-411c-afe6-f1d8e2693607</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
