<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Provinsi_filter_provinsi_id</name>
   <tag></tag>
   <elementGuidId>4bfaba16-2e1a-4bd2-badf-c334b7c32faa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-filter_provinsi_id-container</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'select2-filter_provinsi_id-container' and (text() = '- Pilih Provinsi -' or . = '- Pilih Provinsi -')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@role=‘treeitem’ and contains(text(), Bengkulu)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9f3b13f4-3c39-489e-9d52-b0cb528c184f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>5eed595e-982a-4e95-9da6-4b53e2fdf168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-filter_provinsi_id-container</value>
      <webElementGuid>c63d7a35-e0a5-46de-a654-a280268a8f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>a2715830-9b7a-4682-b0fa-b94083435bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5961469f-13eb-41f5-a790-2f57665d5e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Pilih Provinsi -</value>
      <webElementGuid>984aa677-2ceb-4ed7-8270-ad6e1008a74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-filter_provinsi_id-container&quot;)</value>
      <webElementGuid>b4f99104-a357-492a-bd6f-b596ce87c899</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-filter_provinsi_id-container']</value>
      <webElementGuid>9ebf98cb-aab9-4e5a-9e5d-74952b4000d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table-inputpemilih_id-modal']/div/div/form/div/div/div/span/span/span/span</value>
      <webElementGuid>6d63cb3b-f252-48ef-a315-3e3a5c7b5564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provinsi'])[1]/following::span[4]</value>
      <webElementGuid>2c75a1b0-ff92-484d-9bbe-2575d9543a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter Data Pemilih'])[1]/following::span[4]</value>
      <webElementGuid>515d7ea0-49c4-45ec-bc6d-00b2c5e052e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota/Kabupaten'])[1]/preceding::span[4]</value>
      <webElementGuid>ecfaf2f0-24f6-4ec7-9dc4-d114b49b777e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>e3914ef6-92bb-486e-90f5-1ff4250c791a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-filter_provinsi_id-container' and (text() = '- Pilih Provinsi -' or . = '- Pilih Provinsi -')]</value>
      <webElementGuid>f0bb6a0c-7787-4ec7-82f8-93fafde2191b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
