<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Kecamatan_filter_kecamatan_id</name>
   <tag></tag>
   <elementGuidId>26aa0ca7-3884-4767-805c-91318c81e9f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='filter_kecamatan_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#filter_kecamatan_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3ca0197e-e9aa-4ad9-93fa-6315a6f89038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter_kecamatan_id</value>
      <webElementGuid>8c02dbff-87ac-4fa3-be48-c57f1867df7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filter_kecamatan_id</value>
      <webElementGuid>abf6e043-fcb6-40d5-a106-0ddacd37170a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>268265bf-0d3b-496f-a09d-5e8e019d96b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>comboKelurahan(this)</value>
      <webElementGuid>1099b56c-f4fe-4410-b16b-9a0232cb1508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-to</name>
      <type>Main</type>
      <value>filter_kelurahan_id</value>
      <webElementGuid>3c6a143c-904a-4f6e-90aa-b9df0236fc1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-inputpemilih_id-modal&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/form[1]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-9&quot;]/select[@id=&quot;filter_kecamatan_id&quot;]</value>
      <webElementGuid>ce23676e-3f46-4b0b-8d7d-6fb34ede9c09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='filter_kecamatan_id']</value>
      <webElementGuid>cbff4f66-2f73-4ac4-8eeb-2759ccbb1ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table-inputpemilih_id-modal']/div/div/form/div/div[3]/div/select</value>
      <webElementGuid>867b6930-868b-4e25-b62a-ec118acb213d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>73d7c3ef-5627-4bc7-847f-eadcadf98e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'filter_kecamatan_id' and @name = 'filter_kecamatan_id']</value>
      <webElementGuid>fee2deb6-a6f4-451a-b242-d9a668e07539</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
