<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_KotaKabupaten_filter_kota_id</name>
   <tag></tag>
   <elementGuidId>994911a6-5f0b-43e1-b5b0-b728a81a2526</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter_kota_id</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'filter_kota_id' and @name = 'filter_kota_id']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='filter_kota_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e4902b09-619a-4c1d-a795-aaaa4c9bd819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter_kota_id</value>
      <webElementGuid>c865756f-c05e-4cfb-b114-f32775a79e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filter_kota_id</value>
      <webElementGuid>cd718812-ab2c-4adf-9a22-0bccf0e39c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>1564d29f-09d8-483e-8587-881054500777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>comboKecamatan(this)</value>
      <webElementGuid>1125631c-4c86-4253-8401-e30bed14e1fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-to</name>
      <type>Main</type>
      <value>filter_kecamatan_id</value>
      <webElementGuid>ff1b3505-b6a4-482c-bf7a-1c7e3f32a9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-inputpemilih_id-modal&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/form[1]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-9&quot;]/select[@id=&quot;filter_kota_id&quot;]</value>
      <webElementGuid>d9954e8a-280d-46f9-b085-0dc773dd1575</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='filter_kota_id']</value>
      <webElementGuid>408d3f64-dab9-4622-b7ac-0b8cad324d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table-inputpemilih_id-modal']/div/div/form/div/div[2]/div/select</value>
      <webElementGuid>cd2a38e1-0122-4551-8acf-d5c106806c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>313284af-6296-4afb-93ce-40d700bd4bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'filter_kota_id' and @name = 'filter_kota_id']</value>
      <webElementGuid>fe512b96-659f-4745-816f-04f2cb793c0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
