<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Kelurahan_filter_kelurahan_id</name>
   <tag></tag>
   <elementGuidId>2fd4d7b9-f29c-4523-b5d9-2a0ea7698ce6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='filter_kelurahan_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#filter_kelurahan_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a16f8d3e-bcb2-4f0a-8d58-0abc77255109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter_kelurahan_id</value>
      <webElementGuid>4599ac27-d5de-4d47-9f93-7152211ded6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filter_kelurahan_id</value>
      <webElementGuid>4270bd4c-28a5-436b-b8b6-472ee0ab64b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>5a0a456f-b8c2-4098-a191-e7baef744f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>comboTps(this)</value>
      <webElementGuid>abc94df8-d4a7-48fd-ae52-1ead9ee1837c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-to</name>
      <type>Main</type>
      <value>filter_tps_id</value>
      <webElementGuid>0b10031c-a731-4e55-abf5-a7d925704308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-inputpemilih_id-modal&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/form[1]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-9&quot;]/select[@id=&quot;filter_kelurahan_id&quot;]</value>
      <webElementGuid>a22c07fb-6692-4457-ad40-84aed3a5490b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='filter_kelurahan_id']</value>
      <webElementGuid>fda7a5d9-680c-4ddc-b61b-27cd9a811f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table-inputpemilih_id-modal']/div/div/form/div/div[4]/div/select</value>
      <webElementGuid>0e6b199e-2c5c-4569-ac62-7b457342d600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>ae77cdd4-2a73-4f23-b004-c1b770c210fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'filter_kelurahan_id' and @name = 'filter_kelurahan_id']</value>
      <webElementGuid>f40ef96f-1c04-462d-80a0-5eac267d04ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
