<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_- Pilih TPS -</name>
   <tag></tag>
   <elementGuidId>31f354e9-65a5-48e8-89ba-ec8c70e873e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-filter_tps_id-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-filter_tps_id-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>123eeafa-ec1b-4256-9fa8-5e8dcb2ca800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>41ad2b26-8834-4638-91b5-3e935f02e547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-filter_tps_id-container</value>
      <webElementGuid>4f5d44b4-25b2-4dd7-a2c2-0be6c3b86640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>75e3adf1-0e4e-49e4-820a-c2a06202ea13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c0dd6b36-b5f9-40b0-8ee7-af10cca66bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Pilih TPS -</value>
      <webElementGuid>b4825fb7-ca22-4b99-90ca-ba5132823992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-filter_tps_id-container&quot;)</value>
      <webElementGuid>a5be31e8-66a4-42f8-b210-56ef40f6ceb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-filter_tps_id-container']</value>
      <webElementGuid>8f029cc1-2491-49b2-a551-0243edbe3bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table-inputpemilih_id-modal']/div/div/form/div/div[5]/div/span/span/span/span</value>
      <webElementGuid>fd340fe4-714f-459e-a6e4-6d4112dfcadf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TPS'])[2]/following::span[4]</value>
      <webElementGuid>0b97b66c-c8b7-4ad5-8e29-8db580aa13aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/following::span[6]</value>
      <webElementGuid>c5f49d2c-fbd2-4997-85fe-1c19cf14d618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Filter'])[1]/preceding::span[4]</value>
      <webElementGuid>e77c16d5-0348-4e75-ac5e-aeec5d50dbc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/span/span/span/span</value>
      <webElementGuid>a69b35f1-967d-45bf-855e-c771a23afd09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-filter_tps_id-container' and (text() = '- Pilih TPS -' or . = '- Pilih TPS -')]</value>
      <webElementGuid>f92aa045-5fe5-4806-b80d-9906d4a64230</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
