<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_BagusBaliBaliBengkuluJakartaJawa BaratJawa SelatanJawa TengahJawa TimurKalimantan BaratMaluku</name>
   <tag></tag>
   <elementGuidId>12a862aa-1f82-4cc7-80a8-88d8824b4974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-filter_provinsi_id-results']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-filter_provinsi_id-results</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>e83694d4-68a3-4538-a763-1c47902415e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__options</value>
      <webElementGuid>5062f6fc-101e-410a-9c91-56642824c5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>cb43ef1b-34ff-42bb-92cf-0ab1e5c6ea31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-filter_provinsi_id-results</value>
      <webElementGuid>d7d7acca-4330-4a16-a5f1-f21201dbe1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4279ab87-054d-434b-ad32-ae4a9b18dec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4608ab0b-f130-45c9-8942-7ea84bb4018e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BagusBaliBaliBengkuluJakartaJawa BaratJawa SelatanJawa TengahJawa TimurKalimantan BaratMaluku</value>
      <webElementGuid>537fcb5a-dbb2-4c60-8dc0-d8995e355f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-filter_provinsi_id-results&quot;)</value>
      <webElementGuid>64a78a60-7365-41e5-bd4f-8a350fca038c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='select2-filter_provinsi_id-results']</value>
      <webElementGuid>01a174c9-66a3-4a22-a1a1-88248b7419cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='kt_body']/span/span/span[2]/ul</value>
      <webElementGuid>fbbecb42-626c-464f-b027-e718e1109ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-filter_provinsi_id-results', '&quot;', ')')])[1]/following::ul[1]</value>
      <webElementGuid>39992887-0c24-4a7b-872c-f4fc3b6d59d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::ul[1]</value>
      <webElementGuid>70f87b65-1324-4ce2-b73b-3e07960c9e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul</value>
      <webElementGuid>aeca383d-6b3d-4abd-b5f6-2ebba6e67748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'select2-filter_provinsi_id-results' and (text() = 'BagusBaliBaliBengkuluJakartaJawa BaratJawa SelatanJawa TengahJawa TimurKalimantan BaratMaluku' or . = 'BagusBaliBaliBengkuluJakartaJawa BaratJawa SelatanJawa TengahJawa TimurKalimantan BaratMaluku')]</value>
      <webElementGuid>8307886d-3610-4e76-ab39-19d91a9e34bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
