<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pemilih_nama</name>
   <tag></tag>
   <elementGuidId>906118ca-753f-4ecc-ae5d-99c0c736309d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pemilih_nama</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pemilih_nama']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd055cb4-dbd8-496a-aa15-c0a6e3deb110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pemilih_nama</value>
      <webElementGuid>3370acdd-bcb5-40b7-9e39-e63fc3bb2e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>26dd6207-9fa5-4283-bc06-12c8e1b13b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>7b8a217b-a7ea-43e3-9e31-ef7f11dce989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pemilih_nama</value>
      <webElementGuid>3127b1b3-e29e-47cb-a41a-59ab52fe7263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>475bb9ae-0f00-417f-bf9c-66a6d3c0a606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pemilih_nama&quot;)</value>
      <webElementGuid>6348acac-67a3-4fc4-a445-1c50a0d7ee8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pemilih_nama']</value>
      <webElementGuid>2dddc724-a552-486e-906a-3fa434a007b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_inputpemilih']/div/div/div/div[3]/div/input[2]</value>
      <webElementGuid>ff56ac49-8465-440c-ba57-b538acb0299c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>0d798d37-4067-4a5d-97f5-8b08926471e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pemilih_nama' and @type = 'text' and @name = 'pemilih_nama']</value>
      <webElementGuid>b555234d-30df-4c24-ac7b-3e938dcdd95d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
