<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pemilih_tgl_lahir</name>
   <tag></tag>
   <elementGuidId>2d53922a-d063-4ef1-bf8d-02ece745f5af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pemilih_tgl_lahir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pemilih_tgl_lahir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0d8cc45-2b13-400d-b83a-2d8cff009497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>767243b5-bec6-4121-896c-01d7cf1d783f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm datepicker</value>
      <webElementGuid>96c409cd-6113-4280-8463-c52161b5d5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pemilih_tgl_lahir</value>
      <webElementGuid>41693725-4b6e-467c-ad88-49d3a5854269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pemilih_tgl_lahir</value>
      <webElementGuid>9fc3622b-efde-4761-8f2a-c8b036236992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>02798841-6627-438e-9f18-f45a57c96a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>4fea8787-efdb-495d-93cd-f000507c692c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>77dc0da0-ba2b-4706-b017-e068305caca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pemilih_tgl_lahir&quot;)</value>
      <webElementGuid>f554a66c-1e79-49dd-9549-c05ce7395b68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pemilih_tgl_lahir']</value>
      <webElementGuid>58fb9384-4b8a-4668-8eee-51a4d8ac2a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_inputpemilih']/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>0564a5a0-d525-4d33-9542-4611ae1d2298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>6c4ba6c7-7b7c-4d76-b3c4-f18bea229f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'pemilih_tgl_lahir' and @name = 'pemilih_tgl_lahir' and @placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>8121b6b3-b9d1-481f-a958-af7bd378109a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
