<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pemilih_tempat_lahir</name>
   <tag></tag>
   <elementGuidId>2d5f51ec-e5c7-47d2-9e13-eb5392441601</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pemilih_tempat_lahir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pemilih_tempat_lahir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5df1a91d-6678-4830-bd14-9649eb782439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pemilih_tempat_lahir</value>
      <webElementGuid>0d8c7df0-73bc-420d-b48f-ae850f1f6441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>31389c07-e75f-4ad2-be71-f783a9d0e6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>3c5c5e4a-dab9-444f-aee1-7cc865a0a2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pemilih_tempat_lahir</value>
      <webElementGuid>38b7e0c0-40a8-4ed9-adef-20a59684a8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>fb5fa9fd-77a1-431d-9615-75e82cc1036c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pemilih_tempat_lahir&quot;)</value>
      <webElementGuid>71a06b07-3200-4290-87cd-b2684e4585f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pemilih_tempat_lahir']</value>
      <webElementGuid>7b927100-dcb9-4f19-ac26-7a59710267f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_inputpemilih']/div/div/div[2]/div/div/input</value>
      <webElementGuid>d1347e41-210d-43ed-9fca-e5419bc8350a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>8931cb2f-bbd0-490c-933a-0a6101f3d5cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pemilih_tempat_lahir' and @type = 'text' and @name = 'pemilih_tempat_lahir']</value>
      <webElementGuid>7846c316-fca9-41b8-9b76-50fab731fb60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
