<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pemilih_nik</name>
   <tag></tag>
   <elementGuidId>ab7d142c-c80f-478b-9332-3e9e6b830d56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pemilih_nik</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pemilih_nik']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fca58e66-02c7-4f37-b530-5c9727e66d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pemilih_nik</value>
      <webElementGuid>700d8a5c-07be-4725-9861-c9f5c1b2ed49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>230449da-106d-40d7-b72e-3f5b630b69bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>b209f377-749e-4775-8853-b6c3c755c5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>7c85fd70-5159-41ff-a90a-7ab4f10423ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pemilih_nik</value>
      <webElementGuid>3cda435d-b609-440c-a548-7f031e01eb6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>b9e4f433-0964-474c-9bad-ca73892648f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pemilih_nik&quot;)</value>
      <webElementGuid>1871d163-8c9e-4a3f-831e-ba3e5de72f90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pemilih_nik']</value>
      <webElementGuid>6d96e70b-d91d-4958-86e9-7c93da0278a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_inputpemilih']/div/div/div/div[2]/div/input</value>
      <webElementGuid>a9e04eb0-e6d2-4f4f-a2c4-ce8bb0fdad8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>5f37def6-7520-42a9-8e6a-5d54efd664c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pemilih_nik' and @type = 'text' and @name = 'pemilih_nik']</value>
      <webElementGuid>4d198469-f0d5-406c-a656-1d8fb13d7297</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
