<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pemilih_rt</name>
   <tag></tag>
   <elementGuidId>9f46c5e7-ec49-4dfe-b3a9-2840bdcdb115</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pemilih_rt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pemilih_rt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5f71f28-c0dd-4ea2-8d95-ee5d52106914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pemilih_rt</value>
      <webElementGuid>190571ef-5398-4cf3-9699-416c5665eeb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0f80e478-649b-4a5d-a29d-b68747a7a77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>36bc0601-159a-438b-be15-d45e6bd36444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pemilih_rt</value>
      <webElementGuid>3a1d119e-d0db-4895-bffe-f703df534cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e1e0735d-39ab-47ee-a3f7-fa5581f21edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>39f53273-b05c-4803-b840-4170481189c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pemilih_rt&quot;)</value>
      <webElementGuid>0e64b70a-f0e5-46f9-810f-ee2917d0a63f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pemilih_rt']</value>
      <webElementGuid>1df40ea9-faf0-4b95-8423-afce85146ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_inputpemilih']/div/div/div/div[5]/div/input</value>
      <webElementGuid>240dcf5d-dada-4379-9105-bf230a83b1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>b9dbf06f-a898-4506-8a18-9441d3b6e0d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pemilih_rt' and @type = 'number' and @name = 'pemilih_rt']</value>
      <webElementGuid>ee3d9c88-6c04-4199-bae1-80056e56833f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
