<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_- Pilih Kelurahan -</name>
   <tag></tag>
   <elementGuidId>da28ae37-c9c9-4b73-8e31-4ab7b91f63ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-pemilih_kelurahan_id-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-pemilih_kelurahan_id-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dfa8e356-cc33-469a-a602-3cf45f8ae93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>ae399be3-3a3e-4338-a5d0-9076616be80c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-pemilih_kelurahan_id-container</value>
      <webElementGuid>558a8772-5c28-453f-bd54-db57712e33db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>7666bab2-cee5-4c8b-9d06-cd924c3cc037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6ce71c45-721b-4db9-8fad-0c55b9b53331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> - Pilih Kelurahan -</value>
      <webElementGuid>8e74dcc8-56e2-41ef-9fc6-b487b8497a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-pemilih_kelurahan_id-container&quot;)</value>
      <webElementGuid>7a8040ac-2a65-4ce3-9e2f-a11d76dc2fee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-pemilih_kelurahan_id-container']</value>
      <webElementGuid>4bbb06c6-5e1a-4919-8cd7-44a1ff469e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_inputpemilih']/div/div/div/div[7]/div/span/span/span/span</value>
      <webElementGuid>c9d43674-e3df-49c2-924a-40cc6ff0edb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::span[4]</value>
      <webElementGuid>ce5397b2-8201-423f-b099-fbf138002cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/span/span/span/span</value>
      <webElementGuid>5952ed2e-2e8b-434e-a200-e88529451207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-pemilih_kelurahan_id-container' and (text() = ' - Pilih Kelurahan -' or . = ' - Pilih Kelurahan -')]</value>
      <webElementGuid>6af41d3c-3837-4ab1-8b52-46511b40666e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
