<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_- Pilih Status Kawin -</name>
   <tag></tag>
   <elementGuidId>4350c67c-3405-43f2-97ee-2181e9ceaa6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-pemilih_status_kawin-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-pemilih_status_kawin-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7d8b1c8a-a7e9-4a00-acf4-2a08e58b0777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>ecc85521-f7b6-4b7d-b4d9-1a498c023c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-pemilih_status_kawin-container</value>
      <webElementGuid>b60e9833-2578-422a-b093-cf47ac6874ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>2dee9d74-98a8-413f-9ba4-16272f7e3b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>729364b6-00af-4f8b-b5ac-9f51c5de4f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> - Pilih Status Kawin - </value>
      <webElementGuid>bd5c5cfe-6cac-49eb-bc9f-1085681dfb55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-pemilih_status_kawin-container&quot;)</value>
      <webElementGuid>41b3bb68-373f-471a-a54d-d00ebc69b528</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-pemilih_status_kawin-container']</value>
      <webElementGuid>1a05d02b-09c9-4a30-9201-07b23cd42fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_inputpemilih']/div/div/div[2]/div[4]/div/span/span/span/span</value>
      <webElementGuid>662c8ba5-a719-41fa-9ef6-3c1ce94257a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::span[4]</value>
      <webElementGuid>9c3694af-7c00-4d8b-9ae3-7be9e5688efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/span/span/span</value>
      <webElementGuid>2aff883f-c643-47f5-83bf-77736260d932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-pemilih_status_kawin-container' and (text() = ' - Pilih Status Kawin - ' or . = ' - Pilih Status Kawin - ')]</value>
      <webElementGuid>dcfc9a4f-565a-41e0-861d-745633268d70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
