<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_- Pilih Caleg -</name>
   <tag></tag>
   <elementGuidId>4542f02e-b0fa-49b0-913e-6f8d5739590b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-pemilih_caleg_id-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-pemilih_caleg_id-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>baf7fc9e-a4ab-43ae-a43d-47424e27be5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>7a34d6e6-9e45-4918-a41b-cf97c8382fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-pemilih_caleg_id-container</value>
      <webElementGuid>af86ef2b-a76a-4b01-b8a4-836be4bb6d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>dfeba250-777b-41e3-8862-a80d51a0cfda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bf241d41-6990-4de2-8119-2c6be898c130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Pilih Caleg -</value>
      <webElementGuid>82581e5a-4446-4cb9-a2d3-84fcc703ca9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-pemilih_caleg_id-container&quot;)</value>
      <webElementGuid>f970ddd5-53fb-485c-9aaa-03fb4db581e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-pemilih_caleg_id-container']</value>
      <webElementGuid>8b7d0bc6-856a-47b2-8a55-51de362974fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_inputpemilih']/div/div/div[2]/div[5]/div/span/span/span/span</value>
      <webElementGuid>f0e58901-aacc-4fd5-97f6-14774588f754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[12]/following::span[4]</value>
      <webElementGuid>2e1397cb-a54c-484d-b805-37b4acb34b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/span/span/span/span</value>
      <webElementGuid>f15c17cc-ddfc-461a-a349-db99066f88da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-pemilih_caleg_id-container' and (text() = '- Pilih Caleg -' or . = '- Pilih Caleg -')]</value>
      <webElementGuid>c1ae5a89-f93a-486a-b774-7e1d73448e07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
