<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pemilih_tgl_lahir</name>
   <tag></tag>
   <elementGuidId>d53eacc1-6a0b-4f58-a931-fafdbefaf195</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pemilih_tgl_lahir']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pemilih_tgl_lahir</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c1de31b-aa80-468d-bf31-b778051475ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4c9fbf68-791c-4eef-847c-3fa7fce6f5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm datepicker</value>
      <webElementGuid>84923d07-1bad-4054-a719-19a0f99ddc48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pemilih_tgl_lahir</value>
      <webElementGuid>49f067d8-5bcc-4b01-a026-e7fd1e20a1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pemilih_tgl_lahir</value>
      <webElementGuid>4c0b82ad-5623-4293-8c45-5c753d20cd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>2072eb9f-afeb-4d94-8bb6-610f1c7bb9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>8cb954f9-1025-4c87-af7c-0b8951c82104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b0037ceb-b5d0-483d-a8d6-6e58ddd89035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pemilih_tgl_lahir&quot;)</value>
      <webElementGuid>e3e7b63c-7395-44e8-97a2-d970756bb37f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pemilih_tgl_lahir']</value>
      <webElementGuid>a211f589-962c-40fc-9f8c-9cec39def02a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_inputpemilih']/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>620ac302-dadb-4809-92a9-9dd66b3c2e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>0f5a7170-3022-4238-9e61-34fe0129c681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'pemilih_tgl_lahir' and @name = 'pemilih_tgl_lahir' and @placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>9d5027b3-92ae-43fa-9d84-15fa645d0aee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
