<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Data Pemilih_table-inputpemilih_dtSearch</name>
   <tag></tag>
   <elementGuidId>2c9e2f4d-8e3b-481c-bc87-e34d47edd554</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='table-inputpemilih_dtSearch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#table-inputpemilih_dtSearch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52245061-5531-48a0-ad36-23d61a127b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>30ee602d-2ebb-4be6-abca-6afbee70e0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>92c390c6-c613-40e7-8637-13a02b548354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>table-inputpemilih_dtSearch</value>
      <webElementGuid>6ee5d50c-39a5-452b-9c85-8b48f5784755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Data Pemilih</value>
      <webElementGuid>80433e72-8e9b-4a4d-8483-c18c3e53255a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>provinsi-table</value>
      <webElementGuid>43654969-b8b0-4be3-b5c1-7fa2390564da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-inputpemilih_dtSearch&quot;)</value>
      <webElementGuid>df94662a-eb79-4e12-b6a1-bc7734d05911</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='table-inputpemilih_dtSearch']</value>
      <webElementGuid>1d3a156a-2c84-4fc7-b2fc-3063e93a1a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cardDataPemilih']/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>14dee603-c1d9-49f4-8e24-b1e16c15801a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>31256fa1-0bf6-44da-8f1b-73c6397c8859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'table-inputpemilih_dtSearch' and @placeholder = 'Search Data Pemilih']</value>
      <webElementGuid>97f9d882-a2a4-492a-8978-e20e61f6373e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
