<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_- Pilih Provinsi -</name>
   <tag></tag>
   <elementGuidId>99c4da6a-cc80-49b5-b509-c25d07d3a268</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-filter_provinsi_id-container</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'select2-filter_provinsi_id-container' and (text() = '- Pilih Provinsi -' or . = '- Pilih Provinsi -')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-filter_provinsi_id-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2ed3a701-db77-4875-8f0d-c2e114973f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>f6e2b3c8-e197-423b-ba35-8603dc7f4036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-filter_provinsi_id-container</value>
      <webElementGuid>afa792f6-517b-4650-b3dc-7e98edd0b207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>849918e3-e7c5-416d-8654-a0a33248ab10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>858be42f-2e2b-4f0a-81ee-02e0c40fa07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Pilih Provinsi -</value>
      <webElementGuid>088688af-a6b1-452b-8271-9296edb94ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-filter_provinsi_id-container&quot;)</value>
      <webElementGuid>f4dd3589-596a-4e41-894d-3b458fecca8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-filter_provinsi_id-container']</value>
      <webElementGuid>a69e3e60-2193-4863-bba2-e73d0b6c8190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table-inputpemilih_id-modal']/div/div/form/div/div/div/span/span/span/span</value>
      <webElementGuid>4d3cf16c-c311-48dd-af74-b72ff3faba17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provinsi'])[1]/following::span[4]</value>
      <webElementGuid>aa4982c5-baab-4a04-b2a7-c9f9c88fbdff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter Data Pemilih'])[1]/following::span[4]</value>
      <webElementGuid>71a53449-7cf0-4002-8e1f-a75b30ecb24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota/Kabupaten'])[1]/preceding::span[4]</value>
      <webElementGuid>01981fd2-58d7-4633-841f-880fa3e95d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>6916d1f3-3b2a-4483-b263-773daf034ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-filter_provinsi_id-container' and (text() = '- Pilih Provinsi -' or . = '- Pilih Provinsi -')]</value>
      <webElementGuid>7a1ff9af-97f2-43eb-b107-19069db368bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
