<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>8668a982-90c3-4d99-af13-b2c564ff274a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-pemilih_tps_id-container']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-pemilih_tps_id-container > span.select2-selection__clear</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c7e98535-6b38-45eb-9a10-143eed6ee1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__clear</value>
      <webElementGuid>af89f9c6-2d0a-4d6a-a1b0-f35994fc9fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Remove all items</value>
      <webElementGuid>68b46f0e-b075-4808-a78f-33bf306f9aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>558</value>
      <webElementGuid>5a9228e1-bf41-40d6-aa48-0188b4790cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>2c2bfec2-2808-4497-8051-b9b6db1fbaa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-pemilih_tps_id-container&quot;)/span[@class=&quot;select2-selection__clear&quot;]</value>
      <webElementGuid>8bde6e29-c7d2-4fbf-8676-253ef8818393</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-pemilih_tps_id-container']/span</value>
      <webElementGuid>1fd14cb6-e412-4e80-bc7a-93d1f9ba5671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[13]/following::span[5]</value>
      <webElementGuid>bcca8c94-0f96-4cfa-bfb2-269565d004f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/preceding::span[3]</value>
      <webElementGuid>0e80db9e-c1c7-4ba6-aa83-a1f92c131e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/span/span/span/span/span</value>
      <webElementGuid>58021f43-d0c6-4dfe-8c6b-7c12c2d77103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Remove all items' and (text() = '×' or . = '×')]</value>
      <webElementGuid>ae88c595-acb3-4e0e-94d2-fce88788c154</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
