<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PEMILIH_btn btn-xs btn-icon btn-bg-light btn-icon-warning btn-hover-warning</name>
   <tag></tag>
   <elementGuidId>5d1a4137-6e48-46a6-a500-d5f4b27938e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>33e0b8cd-0fac-4227-8f06-9b8c9405a451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>be762f8b-3624-4ec8-ba82-69afc6082d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>onEdit('bd262e14c25d74947b734bb9eeb75b88')</value>
      <webElementGuid>3f33ad79-7ce7-4da1-9eb2-5c2f016ffbf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-roleable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7c7cf344-506c-4080-95f3-351b18fcbe9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>inputpemilih-update</value>
      <webElementGuid>a8c9a1bf-dba2-4c4b-b83f-60ee09ea73a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-xs btn-icon btn-bg-light btn-icon-warning btn-hover-warning </value>
      <webElementGuid>4e184ee8-97d0-457f-8166-e0055f39b085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>c31f3872-e08b-44af-a178-418fdd5d72fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Update</value>
      <webElementGuid>eb6ac487-5031-4d41-a7b0-34e5966252c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-inputpemilih&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[@class=&quot;align-top&quot;]/a[@class=&quot;btn btn-xs btn-icon btn-bg-light btn-icon-warning btn-hover-warning&quot;]</value>
      <webElementGuid>d715c211-7092-48fc-8668-3465086426f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;onEdit('bd262e14c25d74947b734bb9eeb75b88')&quot;]</value>
      <webElementGuid>c5d10d43-ce18-4548-8b0a-9d9b2d9194f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-inputpemilih']/tbody/tr[2]/td[8]/a[2]</value>
      <webElementGuid>f4c9162d-f4b5-4988-b7c2-36823b957e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PEMILIH'])[3]/following::a[2]</value>
      <webElementGuid>0bbd0186-c169-496a-afdf-ebf4f93bbdc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='curup Tes'])[1]/following::a[2]</value>
      <webElementGuid>aa166f96-0dd9-45ae-ac8d-5128daece816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bisma'])[1]/preceding::a[1]</value>
      <webElementGuid>21e00abd-b97b-469f-85e3-26495840831b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laki-laki'])[2]/preceding::a[1]</value>
      <webElementGuid>20ab2940-10fa-498f-9918-16cf75772de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[6]</value>
      <webElementGuid>8e04e891-f783-422b-9033-d98f82c4613e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[8]/a[2]</value>
      <webElementGuid>0f2f62f4-92ea-48eb-8613-450275b57689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and @title = 'Update']</value>
      <webElementGuid>5c3483eb-49ee-4a91-a020-a5a017122c32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
