<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_PEMILIH_icon far fa-edit</name>
   <tag></tag>
   <elementGuidId>7341d574-91d7-4562-906d-14c28e8d0956</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table-inputpemilih']/tbody/tr[2]/td[8]/a[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>6796cd40-66e8-4b52-b15f-7aefd139ade8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon far fa-edit</value>
      <webElementGuid>384566b8-7b89-4e8a-9925-27609e1f3a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-inputpemilih&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[@class=&quot;align-top&quot;]/a[@class=&quot;btn btn-xs btn-icon btn-bg-light btn-icon-warning btn-hover-warning&quot;]/i[@class=&quot;icon far fa-edit&quot;]</value>
      <webElementGuid>545854c9-1949-4f4d-834e-4f3b4ae6d865</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-inputpemilih']/tbody/tr[2]/td[8]/a[2]/i</value>
      <webElementGuid>847971e4-ca35-4220-a2d9-a5418b9f4fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[8]/a[2]/i</value>
      <webElementGuid>714d9a52-af20-4d02-8e1c-314014594b00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
