<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Dummy</name>
   <tag></tag>
   <elementGuidId>ad121ed3-9290-4de3-869d-fa29ca0aa3d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-pemilih_caleg_id-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-pemilih_caleg_id-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a4893e36-5b2e-4867-907d-59f1b18f2596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>112d7958-b1da-41fa-89fd-851ad3c8a6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-pemilih_caleg_id-container</value>
      <webElementGuid>25a7fce4-3c6d-4600-83e1-dfb38fec70dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>3f932f0b-336c-4bff-a692-7a0be3b35388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>70108a1c-8c2a-4e9b-b017-5f1db55ed9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Dummy</value>
      <webElementGuid>08c2d492-1ca6-4952-ad77-43e1903055da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×Dummy</value>
      <webElementGuid>cc0c2644-e439-42f4-984a-27d509edcf8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-pemilih_caleg_id-container&quot;)</value>
      <webElementGuid>1ab7cef4-2e83-4207-8b53-0192a0b4741b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-pemilih_caleg_id-container']</value>
      <webElementGuid>394fda8e-aef6-4910-889c-02cae9c0cbe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_inputpemilih']/div/div/div[2]/div[5]/div/span/span/span/span</value>
      <webElementGuid>3820451e-4246-401d-a687-7a013337e70f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[12]/following::span[4]</value>
      <webElementGuid>c0a490d2-bc1c-41f3-bf4a-9f13039a5512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/span/span/span/span</value>
      <webElementGuid>827fde20-e6d7-4e39-b3f5-ed39c6ffc4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-pemilih_caleg_id-container' and @title = 'Dummy' and (text() = '×Dummy' or . = '×Dummy')]</value>
      <webElementGuid>46d62e44-7796-4086-9642-69d4d353df22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
