<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>52653e54-7b09-4b0a-a079-8a67ec079528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-pemilih_tps_id-container']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-pemilih_tps_id-container > span.select2-selection__clear</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>90dac3f5-6c68-4d9f-bda3-1fac61698c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__clear</value>
      <webElementGuid>9bc695d6-6da9-4612-8af8-ca00aa96155f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Remove all items</value>
      <webElementGuid>71c1ff06-45a1-4308-ba5f-60b9db9924b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>8a8eeb80-0297-4ced-b572-c4020f1c1c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>14fdadd8-afcf-462d-b0e6-c550d7d55391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-pemilih_tps_id-container&quot;)/span[@class=&quot;select2-selection__clear&quot;]</value>
      <webElementGuid>95ca1e51-8ec5-4485-80c2-665e28d5028f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-pemilih_tps_id-container']/span</value>
      <webElementGuid>c656951a-87ae-4bc9-b184-0268a72baabe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[13]/following::span[5]</value>
      <webElementGuid>4126de19-43ea-473b-a342-2aba8b24a741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/preceding::span[3]</value>
      <webElementGuid>020fb2da-1171-4293-98e9-d47951942f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/span/span/span/span/span</value>
      <webElementGuid>10b9b957-527d-49cb-8798-d596b37e2d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Remove all items' and (text() = '×' or . = '×')]</value>
      <webElementGuid>6e69d143-574b-4468-9def-28b4035d5a10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
