<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_delprov</name>
   <tag></tag>
   <elementGuidId>9e9cfff6-a6ba-4bca-b4fc-551b9d9b2ad4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-filter_kota_id-container > span.select2-selection__clear</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'Remove all items' and (text() = '×' or . = '×')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@data-select2-id='30']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d3445cda-0a27-4e7a-8f35-605f87983cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__clear</value>
      <webElementGuid>d95b6335-a558-423a-a8e3-e69f353964d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Remove all items</value>
      <webElementGuid>bbbc5a12-9c01-4af5-b2c4-59d3a8288852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>138</value>
      <webElementGuid>12518000-828c-4a57-be9c-2b0e1a9b4de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>74d57589-66b4-4f56-9ca3-f02f3828e4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-filter_kota_id-container&quot;)/span[@class=&quot;select2-selection__clear&quot;]</value>
      <webElementGuid>dc9c9094-bdfa-4b4e-a597-f18ace374a16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-filter_kota_id-container']/span</value>
      <webElementGuid>4836e60c-9b56-4023-821e-4a581fc6936a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota/Kabupaten'])[1]/following::span[5]</value>
      <webElementGuid>ee7f8f96-6df0-497b-9a32-4d695a9846b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan'])[1]/preceding::span[3]</value>
      <webElementGuid>59cbfdf4-ac32-41f8-9e8c-83f3f07597eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Pilih Kecamatan -'])[2]/preceding::span[3]</value>
      <webElementGuid>1ba3c840-539c-4e5c-a848-5b7423beb438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span/span/span/span</value>
      <webElementGuid>0608552a-d6a0-4845-b057-c007f5036be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Remove all items' and (text() = '×' or . = '×')]</value>
      <webElementGuid>c98d440b-6e57-4578-ac0e-230af22a98f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
